//Async
setTimeout(()=>{
console.log("time1")
},7000)
setTimeout(()=>{
console.log("time2")
},1000)
setTimeout(()=>{
console.log("time3")
},5000)
setTimeout(()=>{
console.log("time4")
},3000)

console.log(1)
console.log(2)
console.log(3)
console.log(4)
console.log(5)
console.log(6)
console.log(7)